version: '3.8'

services:
  mariadb:
    build:
      context: ./docker/mariadb
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "127.0.0.1:3307:3306"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 128M
    restart: always
    networks:
      - webserver
  apache:
    build:
      context: ./docker/apache/php/7.4
      args:
        php_version: ${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-apache
    hostname: webserver.sf
    domainname: webserver
    volumes:
      - ./docker/apache/php/7.4/vhost.conf:/etc/apache2/sites-available/vhost.conf
      - ./docker/apache/php/7.4/abcis.sf5.conf:/etc/apache2/sites-available/abcis.sf5.conf
      - ./docker/apache/php/7.4/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./docker/apache/php/7.4/config/browscap.ini:/usr/local/etc/php/conf.d/browscap.ini
      - ./www:/var/www/html
    ports:
      - "${PHP_PORT}:80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: 'always'
    links: 
      - mariadb
    depends_on: 
      - mariadb  
    networks:
      - webserver
networks:
  webserver: