version: '3.8'
services:
  server:
    build: ./apache
    container_name: server-apache
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - '8000:80'
    volumes:
      - './apache/php/vhost.conf:/etc/apache2/sites-available/vhost.conf'
      - './apache/php/docker.abcis.conf:/etc/apache2/sites-available/docker.abcis.conf'
      - './apache/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini'
      - './app:/var/www/html'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 1024M
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3307:3306'
    volumes:
      - './database:/var/lib/mysql'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
volumes:
  database: null
networks:
  frontend: null
  backend: null
