version: '3'

services:
  apache:
    build:
      context: ./docker/apache/php/7.4
      args:
        php_version: ${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-apache
    hostname: server.web
    domainname: server
    volumes:
      - ./docker/apache/php/7.4/vhost.conf:/etc/apache2/sites-available/vhost.conf
      - ./docker/apache/php/7.4/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./docker/apache/php/7.4/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./www:/var/www/html
    ports:
      - "${PHP_PORT}:80"
    restart: 'always'
    depends_on: 
      - mariadb
    networks:
      - database
      - webserver
  mariadb:
    build:
      context: ./docker/mariadb
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-maridb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "127.0.0.1:3307:3306"
    restart: always
    networks:
      - database
networks:
    database:
    webserver:
